services:
  app:
    container_name: ${PROJECT_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT}:80"
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
